### ISSUE TITLE
Failed to create mod instance. ModID: northerncompass

### ISSUE THREAD

**Issue by SissyTrashQueen** [LXGaming/NorthernCompass#1]
MC VERSION: 1.15.2
Forge: 31.2.0
Northern Compass: 1.15.2-1.0.0

Forge crashes at start

[gist with the stuff](https://gist.github.com/slard3/957dd7ad9e17816b03b4a4708da0380f)

**Comment by LXGaming** [comment]
Try Forge 1.15.2-31.2.5 or higher

**Comment by SissyTrashQueen** [comment]
Thanks for the answer, it works now :)

**Comment by SissyTrashQueen** [comment]
Something I just noticed, the compass doesn't seem to point North if [Quark's Compasses Work Everywhere feature](https://quark.vazkii.net/#features) is enabled
I have to disable their feature for this mod to work. Now I'm closing this for good.
