### ISSUE TITLE
Not Compatible With Quark

### ISSUE THREAD

**Issue by MrTailson** [LXGaming/NorthernCompass#2]
I downloaded Quark, another mod for Minecraft, and I believe it causes changes to the compass, and it's taking priority over this mod. I'm unsure. 

Quark Mod - https://quark.vazkii.net/#features
Look under the "Tweaks" tab on the Wiki and you should find it changes how the compass and clock work.

**Comment by LXGaming** [comment]
Set `Compasses Work Everywhere` to `false` in the `quark-common.toml`

**Comment by MrTailson** [comment]
> Set `Compasses Work Everywhere` to `false` in the `quark-common.toml`

Aww, really? Okay then.
