### ISSUE TITLE
Doesn't work in modpack (1.12.2)

### ISSUE THREAD

**Issue by ghost** [LXGaming/NorthernCompass#4]
[modlist.txt](https://github.com/LXGaming/NorthernCompass/files/7795398/modlist.delete.later.txt)

I've spent hours trying to narrow it down, but there is simply no easy way to find which mod has the conflict. Would really love for this to work, especially because it seems so simple?

**Comment by LXGaming** [comment]
Is the modpack available on CurseForge or something?

**Comment by LXGaming** [comment]
Need more information.
