### ISSUE TITLE
[Issue] Bug with Northern Compass and Crossbowverhaul

### ISSUE THREAD

**Issue by MrHazMat** [LXGaming/NorthernCompass#5]
For some unexplained reason, Northern Compass prevents the normal crossbow from Crossbowverhaul charging animation to play.

**Versions**
Northern Compass: 1.0.8
Crossbowverhaul: 1.2.4
Forge: 39.0.75
Minecraft: 1.18.1

**Comment by LXGaming** [comment]
My mistake, I'm modifing the ItemProperties on `RegistryEvent.Register<Item>` instead of `FMLClientSetupEvent` as per the [Forge Documentation](https://mcforge.readthedocs.io/en/1.18.x/models/itemproperties/)

**Comment by LXGaming** [comment]
Fix is available on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/northerncompass/files/3647910) or [GitHub](https://github.com/LXGaming/NorthernCompass/releases/tag/v1.18.1-1.0.9)

Thanks for reporting
