### ISSUE TITLE
[Suggestion] Add toggle to allow limiting north pointing only in Overworld

### ISSUE THREAD

**Issue by alexiscoutinho** [LXGaming/NorthernCompass#7]
I really like the idea of the mod, but could a toggle setting be added to let users switch between the mod affecting "Only Overworld" or "All dimensions"? ;)

**Comment by LXGaming** [comment]
Implemented in [v1.20.1-1.1.0](https://github.com/LXGaming/NorthernCompass/releases/tag/v1.20.1-1.1.0).

You can setup overworld only by using the following configuration:
```json
{
  "dimensionTypeFallback": false,
  "dimensionTypes": {
    "minecraft:overworld": true,
    "minecraft:overworld_caves": true,
    "minecraft:the_nether": null,
    "minecraft:the_end": null
  }
}
```
