### ISSUE TITLE
Config option backport

### ISSUE THREAD

**Issue by anoomolu** [LXGaming/NorthernCompass#8]
Hiya! Firstly, thank you for making this mod, just adds to the vanilla experience especially with Reduced Debug Info on.

Until recently I was playing on 1.20.1, and returning to 1.16 I noticed the config option to disable compass functionality wasn't there. It's a niche request but would you be able to add this option to the 1.16.5 release? 

No worries if you'd rather not, thanks either way ^^

**Comment by LXGaming** [comment]
Absolutely, [v1.16.5-1.1.2](https://github.com/LXGaming/NorthernCompass/releases/tag/v1.16.5-1.1.2), If you want this on CurseForge or Modrinth let me know and I can upload it there as well.

Additional backports:
- [v1.19.4-1.1.2](https://github.com/LXGaming/NorthernCompass/releases/tag/v1.19.4-1.1.2)
- [v1.18.2-1.1.2](https://github.com/LXGaming/NorthernCompass/releases/tag/v1.18.2-1.1.2)
- [v1.17.1-1.1.2](https://github.com/LXGaming/NorthernCompass/releases/tag/v1.17.1-1.1.2)
- [v1.15.2-1.1.2](https://github.com/LXGaming/NorthernCompass/releases/tag/v1.15.2-1.1.2)
- [v1.14.4-1.1.2](https://github.com/LXGaming/NorthernCompass/releases/tag/v1.14.4-1.1.2)

**Comment by anoomolu** [comment]
Thank you so much <3

I'm fine with using the release on Github, maybe people browsing CF/Modrinth might find it useful?
