### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by Steveplays28** [LXGaming/NorthernCompass#9]
Hi, a 1.21 update would be awesome.
Thank you LXGaming for the great mod!

**Comment by LXGaming** [comment]
No problem, I've updated NorthernCompass to [1.20.6](https://github.com/LXGaming/NorthernCompass/releases/tag/v1.20.6-1.1.3) and [1.21](https://github.com/LXGaming/NorthernCompass/releases/tag/v1.21-1.1.3) (Also available on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/northerncompass) and [Modrinth](https://modrinth.com/mod/northerncompass)).

**Comment by Steveplays28** [comment]
Thank you so much!
